/**
 * Action types dispatched throughout the system
 */
export const actionTypes = {
    search: {
        'SEARCH_TERM_CHANGE': 'SEARCH_TERM_CHANGE',
        'GET_SEARCH_PEERS': 'GET_SEARCH_PEERS',
        'GET_SEARCH_PEERS_SUCCESS': 'GET_SEARCH_PEERS_SUCCESS',
        'GET_SEARCH_PEERS_FAILURE': 'GET_SEARCH_PEERS_FAILURE',
        'GET_META_DATA': 'GET_META_DATA',
        'GET_META_DATA_SUCCESS': 'GET_META_DATA_SUCCESS',
        'GET_META_DATA_FAILURE': 'GET_META_DATA_FAILURE'
    },
    stock: {
        'GET_STOCK_PRICE_DATA': 'GET_STOCK_PRICE_DATA',
        'GET_STOCK_PRICE_DATA_SUCCESS': 'GET_STOCK_PRICE_DATA_SUCCESS',
        'GET_STOCK_PRICE_DATA_FAILURE': 'GET_STOCK_PRICE_DATA_FAILURE'
    }
}